import Head from 'next/head'
import Image from 'next/image'
import { mutate } from 'swr'
import { getStripe } from '../utils/getStripe'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react'
import { Stripe } from '@stripe/stripe-js'

export default function Home() {

  const [isLoading, setIsLoading] = useState(false)

  const fetchSession = async (packageTier) => {
      // Default options are marked with *
      const response = await fetch('/api/checkout_session', {
        method: 'POST', 
        mode: 'cors', // no-cors, *cors, same-origin
        cache: 'no-cache',
        credentials: 'same-origin',
        headers: {
          'Content-Type': 'application/json'          
        },
        redirect: 'follow',
        referrerPolicy: 'no-referrer',
        body: JSON.stringify({ packageTier }) // body data type must match "Content-Type" header
      });

      return response.json(); // parses JSON response into native JavaScript objects
  }

  const onSubmit = async (event) => {
    setIsLoading(true)
    event.preventDefault();
    

    const session = await fetchSession('basic')

    const stripe = await getStripe()

    const { error } = await stripe.redirectToCheckout({
      // Make the id field from the Checkout Session creation API response
      // available to this file, so you can provide it as parameter here
      // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
      sessionId: session.id,
    })
    // If `redirectToCheckout` fails due to a browser or network
    // error, display the localized error message to your customer
    // using `error.message`.
    console.warn(error.message)

    setIsLoading(false)
  }

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Pester</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <button
          onClick={onSubmit}
        >
          { isLoading ? 'loading...' : 'Purchase'}
        </button>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
